/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LayoutComponent {
        /**
          * * Data url to fetch the csv file from. Should be relative to where the component is placed.
         */
        "dataUrl": any;
        "selectedRange": Array<Object>;
    }
    interface LeftPanel {
        "data": any;
        "selectedDataset": {
            id: string;
            name: string;
            url: string;
            description: string;
            category: string;
            date: string;
            group: string;
            formatType: string;
        };
    }
    interface ParallelCoordinates {
        "completeData": Array<Object>;
        "singleData": string;
    }
    interface SecComponent {
    }
}
declare global {
    interface HTMLLayoutComponentElement extends Components.LayoutComponent, HTMLStencilElement {
    }
    var HTMLLayoutComponentElement: {
        prototype: HTMLLayoutComponentElement;
        new (): HTMLLayoutComponentElement;
    };
    interface HTMLLeftPanelElement extends Components.LeftPanel, HTMLStencilElement {
    }
    var HTMLLeftPanelElement: {
        prototype: HTMLLeftPanelElement;
        new (): HTMLLeftPanelElement;
    };
    interface HTMLParallelCoordinatesElement extends Components.ParallelCoordinates, HTMLStencilElement {
    }
    var HTMLParallelCoordinatesElement: {
        prototype: HTMLParallelCoordinatesElement;
        new (): HTMLParallelCoordinatesElement;
    };
    interface HTMLSecComponentElement extends Components.SecComponent, HTMLStencilElement {
    }
    var HTMLSecComponentElement: {
        prototype: HTMLSecComponentElement;
        new (): HTMLSecComponentElement;
    };
    interface HTMLElementTagNameMap {
        "layout-component": HTMLLayoutComponentElement;
        "left-panel": HTMLLeftPanelElement;
        "parallel-coordinates": HTMLParallelCoordinatesElement;
        "sec-component": HTMLSecComponentElement;
    }
}
declare namespace LocalJSX {
    interface LayoutComponent {
        /**
          * * Data url to fetch the csv file from. Should be relative to where the component is placed.
         */
        "dataUrl"?: any;
        "selectedRange"?: Array<Object>;
    }
    interface LeftPanel {
        "data"?: any;
        "onLoadDataset"?: (event: CustomEvent<any>) => void;
        "selectedDataset"?: {
            id: string;
            name: string;
            url: string;
            description: string;
            category: string;
            date: string;
            group: string;
            formatType: string;
        };
    }
    interface ParallelCoordinates {
        "completeData"?: Array<Object>;
        "onBrushCompleted"?: (event: CustomEvent<Array<Object>>) => void;
        "singleData"?: string;
    }
    interface SecComponent {
        "onTodoCompleted"?: (event: CustomEvent<Array<Object>>) => void;
    }
    interface IntrinsicElements {
        "layout-component": LayoutComponent;
        "left-panel": LeftPanel;
        "parallel-coordinates": ParallelCoordinates;
        "sec-component": SecComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "layout-component": LocalJSX.LayoutComponent & JSXBase.HTMLAttributes<HTMLLayoutComponentElement>;
            "left-panel": LocalJSX.LeftPanel & JSXBase.HTMLAttributes<HTMLLeftPanelElement>;
            "parallel-coordinates": LocalJSX.ParallelCoordinates & JSXBase.HTMLAttributes<HTMLParallelCoordinatesElement>;
            "sec-component": LocalJSX.SecComponent & JSXBase.HTMLAttributes<HTMLSecComponentElement>;
        }
    }
}
